# Generated by Django 5.0.6 on 2024-05-13 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.productos'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='detalle_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.detallepedido'),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='id_transaccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.transacciones'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='id_envase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.envases'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='id_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.marcas'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='id_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.paises'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='id_sabor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.sabores'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='id_tipoAlimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.tipoalimento'),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='id_metodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.metodos'),
        ),
        migrations.AlterField(
            model_name='transacciones',
            name='id_tarjeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.tarjetas'),
        ),
    ]
