# Generated by Django 5.0.6 on 2024-05-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_alter_detallepedido_id_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='num_tarjeta',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
