# Generated by Django 5.0.6 on 2024-05-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_alter_usuarios_direccion_envio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
