# Generated by Django 5.0.6 on 2024-05-13 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0005_alter_usuarios_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='direccion_envio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='num_tarjeta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
