# Generated by Django 5.0.6 on 2024-05-14 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0009_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
