# Generated by Django 5.0.6 on 2024-05-15 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0012_alter_customuser_email_alter_customuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='detalle_pedido',
        ),
        migrations.CreateModel(
            name='DetalleCarrito',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('id_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.carrito')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.productos')),
            ],
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
    ]
