# Generated by Django 5.0.6 on 2024-05-15 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0014_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
