# Generated by Django 5.0.6 on 2024-05-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0017_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='codigo_postal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
