# Generated by Django 5.0.6 on 2024-05-16 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0018_customuser_codigo_postal_customuser_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
