# Generated by Django 5.0.6 on 2024-05-16 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0019_alter_customuser_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecarrito',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('Por Pagar', 'Por Pagar'), ('Pagado', 'Pagado'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado')], default='Por Pagar', max_length=20)),
                ('cantidad', models.IntegerField()),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.pedidos')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.productos')),
            ],
        ),
    ]
