# Generated by Django 5.0.6 on 2024-05-16 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0020_detallecarrito_total_detallepedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecarrito',
            name='total',
        ),
        migrations.AddField(
            model_name='carrito',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
