# Generated by Django 5.0.6 on 2024-05-16 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0021_remove_detallecarrito_total_carrito_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='id_carrito',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='id_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
