# Generated by Django 5.0.6 on 2024-05-16 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0022_remove_pedidos_id_carrito_pedidos_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
