# Generated by Django 5.0.6 on 2024-05-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0024_alter_pedidos_id_transaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='estado',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='estado',
            field=models.CharField(choices=[('Por Pagar', 'Por Pagar'), ('Pagado', 'Pagado'), ('Enviado', 'Enviado'), ('Entregado', 'Entregado')], default='Pagado', max_length=20),
        ),
    ]
