# Generated by Django 5.0.6 on 2024-05-16 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0026_remove_customuser_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacciones',
            name='id_metodo',
        ),
        migrations.RemoveField(
            model_name='transacciones',
            name='id_tarjeta',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='num_tarjeta',
        ),
        migrations.AddField(
            model_name='transacciones',
            name='fecha_vencimiento',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='transacciones',
            name='nombre_tarjeta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transacciones',
            name='tarjeta',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.DeleteModel(
            name='Metodos',
        ),
        migrations.DeleteModel(
            name='Tarjetas',
        ),
    ]
